name: Tests on push
on: push
  
  
permissions:
  contents: read

jobs:
  job_1:
    runs-on: self-hosted
    
    steps:
    
    - name: Actions
      uses: actions/checkout@v3
      
    - name: 1st Test
      uses: ./.github/workflows/push.yml
