name: Tests on push
on: push
  
  
permissions:
  contents: read

jobs:
  job_1:
    runs-on: self-hosted
    
    steps:
    
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/push.yml
